### ISSUE TITLE
Transition to gatsby

### ISSUE THREAD

**Issue by NobbZ** [NobbZ/blog-nobbz-dev#189]
The major reimplementation of the blog using [gatsby JS](https://www.gatsbyjs.com) already suceeded in #187.

Now there are still some details missing:

* [x] there is currently no support for tags
  * [x] tags are not displayed on the article page (#190)
  * [x] there is no index for tags (#191)
* [x] the author is completely missing from the article and preview pages (#192)
* [ ] there is no link to the source code (#193)
* [ ] there is no "build with" (#194)

**Comment by NobbZ** [comment]
I will drop gatsby and move to something else.
